options:
  logging: CLOUD_LOGGING_ONLY

steps:
- name: gcr.io/cloud-builders/docker
  args:
    [
      "build",
      "-f",
      "frontend/Dockerfile",
      "-t",
      "us-central1-docker.pkg.dev/test1-482614/uber-repo/uber-frontend:$SHORT_SHA",
      "frontend"
    ]

- name: bash
  entrypoint: bash
  args:
    - -c
    - |
      echo "=== FRONTEND DIR ==="
      ls -la Frontend
      echo "=== ENV FILE ==="
      cat Frontend/.env.production || echo "MISSING ENV FILE"


images:
- "us-central1-docker.pkg.dev/test1-482614/uber-repo/uber-frontend:$SHORT_SHA"
