options:
  logging: CLOUD_LOGGING_ONLY

steps:
- name: gcr.io/cloud-builders/docker
  args:
    [
      "build",
      "-f",
      "backend/Dockerfile",
      "-t",
      "us-central1-docker.pkg.dev/test1-482614/uber-repo/uber-backend:$SHORT_SHA",
      "backend"
    ]

images:
- "us-central1-docker.pkg.dev/test1-482614/uber-repo/uber-backend:$SHORT_SHA"
